# Electric Vehicle Population

### Exploratory Data Analysis (EDA) & Machine Learning Project — Question Bank

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

###  Beginner (Pandas Practice)

In [3]:
df=pd.read_csv("EV.csv")
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JN1AZ0CP5C,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,7.0,153331706,POINT (-117.90454 48.54657),AVISTA CORP,5.306595e+10
1,JTMABABA7P,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,253586308,POINT (-120.71847 46.55029),PACIFICORP,5.307700e+10
2,1N4AZ1CP1J,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,37.0,333135022,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5UX43EU09S,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,40.0,23.0,267525737,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303594e+10
4,3C3CFFGE5F,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,87.0,2.0,474468501,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10

### 1. How many rows and columns are there?

In [4]:
rows,columns=df.shape
print("Number of rows: ",rows)
print("Number of columns: ",columns)

Number of rows:  279780
Number of columns:  16

### 2. What are the data types of every column?

In [5]:
df.dtypes

VIN (1-10)                                               str
County                                                   str
City                                                     str
State                                                    str
Postal Code                                          float64
Model Year                                             int64
Make                                                     str
Model                                                    str
Electric Vehicle Type                                    str
Clean Alternative Fuel Vehicle (CAFV) Eligibility        str
Electric Range                                       float64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                         str
Electric Utility                                         str
2020 Census Tract                                    float64
dtype: object

### 3. Are there any missing values?

In [6]:
df.isna().sum()

VIN (1-10)                                             0
County                                                24
City                                                  24
State                                                  0
Postal Code                                           24
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                        11
Legislative District                                 700
DOL Vehicle ID                                         0
Vehicle Location                                     109
Electric Utility                                      24
2020 Census Tract                                     24
dtype: int64

### 4. Which columns contain missing values?

In [7]:
df.isnull().sum()[df.isnull().sum()>0]

County                   24
City                     24
Postal Code              24
Electric Range           11
Legislative District    700
Vehicle Location        109
Electric Utility         24
2020 Census Tract        24
dtype: int64

### 5. Remove duplicate records (if any).

In [8]:
df.duplicated().any()

np.False_

### 6. Display summary statistics.

In [9]:
df.describe(include="all")

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
count,279780,279756,279756,279780,279756.000000,279780.000000,279780,279780,279780,279780,279769.000000,279080.000000,2.797800e+05,279671,279756,2.797560e+05
unique,17072,253,894,52,NaN,NaN,47,187,2,3,NaN,NaN,NaN,1115,77,NaN
top,7SAYGDEE7P,King,Seattle,WA,NaN,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,NaN,NaN,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),NaN
freq,1187,138130,43250,279093,NaN,NaN,114847,60035,223884,177937,NaN,NaN,NaN,6776,99568,NaN
mean,NaN,NaN,NaN,NaN,98176.111447,2022.074072,NaN,NaN,NaN,NaN,39.172256,28.827841,2.462994e+08,NaN,NaN,5.297189e+10
std,NaN,NaN,NaN,NaN,2577.398040,3.059852,NaN,NaN,NaN,NaN,78.230356,14.908133,6.346205e+07,NaN,NaN,1.636194e+09
min,NaN,NaN,NaN,NaN,1030.000000,1999.000000,NaN,NaN,NaN,NaN,0.000000,1.000000,4.385000e+03,NaN,NaN,1.001020e+09
25%,NaN,NaN,NaN,NaN,98052.000000,2021.000000,NaN,NaN,NaN,NaN,0.000000,17.000000,2.213867e+08,NaN,NaN,5.303301e+10
50%,NaN,NaN,NaN,NaN,98133.000000,2023.000000,NaN,NaN,NaN,NaN,0.000000,32.000000,2.629453e+08,NaN,NaN,5.303303e+10
75%,NaN,NaN,NaN,NaN,98382.000000,2024.000000,NaN,NaN,NaN,NaN,32.000000,42.000000,2.790832e+08,NaN,NaN,5.305394e+10
max,NaN,NaN,NaN,NaN,99517.000000,2027.000000,NaN,NaN,NaN,NaN,337.000000,49.000000,4.791150e+08,NaN,NaN,6.601095e+10

### 7. Count unique values in every column.

In [10]:
df.nunique()

VIN (1-10)                                            17072
County                                                  253
City                                                    894
State                                                    52
Postal Code                                            1119
Model Year                                               23
Make                                                     47
Model                                                   187
Electric Vehicle Type                                     2
Clean Alternative Fuel Vehicle (CAFV) Eligibility         3
Electric Range                                          113
Legislative District                                     49
DOL Vehicle ID                                       279780
Vehicle Location                                       1115
Electric Utility                                         77
2020 Census Tract                                      2374
dtype: int64

### 8. Which manufacturer has the most EVs?

In [11]:
top_manufacturer=df["Make"].value_counts().idxmax()
count=df["Make"].value_counts().max()
print("Manufacturer with most EV's: ",top_manufacturer)
print("Number of EV's: ",count)

Manufacturer with most EV's:  TESLA
Number of EV's:  114847

### 9. Which model appears the most?

In [12]:
most_common=df["Model"].value_counts().idxmax()
count=df["Model"].value_counts().max()
print("Most common Models are: ",most_common)
print("Count of the models: ",count)

Most common Models are:  MODEL Y
Count of the models:  60035

### 10. How many different EV models are there?

In [13]:
models=sorted(df["Model"].unique())
print("Numbers of Models: ",models)

Numbers of Models:  ['330E', '500', '500E', '530E', '550E', '740E', '745E', '745LE', '750E', '918', 'A3', 'A6', 'A7 E', 'A8 E', 'ACCORD', 'AIR', 'AMG GT', 'ARIYA HATCHBACK', 'ARIYA MPV', 'AVIATOR', 'B-CLASS', 'BENTAYGA', 'BLAZER', 'BOLT', 'BOLT EUV', 'BOLT EV', 'BRIGHTDROP', 'BZ', 'BZ4X', 'C-CLASS', 'C-MAX', 'C40', 'CAYENNE', 'CHARGER', 'CITY', 'CLARITY', 'CONTINENTAL', 'CORSAIR', 'COUNTRYMAN', 'CROSSTREK', 'CT6', 'CX-70', 'CX-90', 'CYBERTRUCK', 'E-CLASS', 'E-GOLF', 'E-TRON', 'E-TRON GT', 'E-TRON SPORTBACK', 'EDV', 'ELR', 'EQ FORTWO', 'EQB-CLASS', 'EQE-CLASS SEDAN', 'EQE-CLASS SUV', 'EQS-CLASS SEDAN', 'EQS-CLASS SUV', 'EQUINOX', 'ESCAPE', 'ESPRINTER', 'EV6', 'EV9', 'EX30', 'EX30 CC', 'EX40', 'EX90', 'F-150', 'FLYING SPUR', 'FOCUS', 'FORTWO', 'FORTWO ELECTRIC DRIVE', 'FUSION', 'G-CLASS', 'G80', 'GLC-CLASS', 'GLE-CLASS', 'GRANCABRIO', 'GRAND CHEROKEE', 'GRAVITY', 'GV60', 'GV70', 'HARDTOP', 'HORNET', 'HUMMER EV PICKUP', 'HUMMER EV SUV', 'I-MIEV', 'I-PACE', 'I3', 'I4', 'I5', 'I7', 'I8', 'ID. BUZZ', 'ID.4', 'IONIQ', 'IONIQ 5', 'IONIQ 5 N', 'IONIQ 6', 'IONIQ 9', 'IX', 'KARMA', 'KONA', 'LEAF', 'LYRIQ', 'M5', 'MACAN', 'MIRAI', 'MODEL 3', 'MODEL S', 'MODEL X', 'MODEL Y', 'MUSTANG MACH-E', 'MX-30', 'NIRO', 'NX', 'OCEAN', 'ONE', 'OPTIMA', 'OPTIQ', 'OUTLANDER', 'PACIFICA', 'PANAMERA', 'POLESTAR 3', 'POLESTAR 4', 'PRIUS', 'PRIUS PRIME (PHEV)', 'PROLOGUE', 'PROMASTER 3500', 'PS2', 'Q4', 'Q5', 'Q5 E', 'Q6', 'Q8', 'R1S', 'R1T', 'RANGE ROVER', 'RANGE ROVER SPORT', 'RANGER', 'RAV4', 'RAV4 PRIME (PHEV)', 'RCV', 'REVUELTO', 'ROADSTER', 'RS E-TRON GT', 'RX', 'RZ', 'S E-TRON GT', 'S-CLASS', 'S6', 'S60', 'S90', 'SANTA FE', 'SIERRA', 'SILVERADO', 'SL-CLASS', 'SOLTERRA', 'SONATA', 'SORENTO', 'SOUL', 'SPARK', 'SPECTRE', 'SPORTAGE', 'SQ6', 'SQ8', 'TAYCAN', 'TONALE', 'TRANSIT', 'TRANSIT CONNECT ELECTRIC', 'TUCSON', 'TX', 'URUS', 'V60', 'VF 8', 'VISTIQ', 'VOLT', 'WAGONEER S', 'WHEEGO', 'WRANGLER', 'X3', 'X5', 'XC40', 'XC60', 'XC90', 'XM', 'ZDX', 'ZEVO']